{"name": "test_create_user_invalid_token", "status": "broken", "statusDetails": {"message": "jsonschema.exceptions.ValidationError: {'message': 'Invalid token'} is not of type 'array'\n\nFailed validating 'type' in schema:\n    {'type': 'array',\n     'items': {'type': 'object',\n               'properties': {'field': {'type': 'string'},\n                              'message': {'type': 'string'}},\n               'required': ['message']}}\n\nOn instance:\n    {'message': 'Invalid token'}", "trace": "base_url = 'https://gorest.co.in', end_point = '/public/v2/users/'\n\n    @allure.feature(\"User Management\")\n    @allure.story(\"Negative Scenarios\")\n    @pytest.mark.negative\n    def test_create_user_invalid_token(base_url, end_point):\n        \"\"\"Verify creating a user with an invalid token fails (401)\"\"\"\n        data = {\"name\": \"invalid_user\", \"email\": \"invalid@user.com\", \"gender\": \"male\", \"status\": \"active\"}\n        bad_headers = {\"Authorization\": \"Bearer invalidtoken123\"}\n    \n        post_response = requests.post(base_url + end_point, headers=bad_headers, json=data, timeout=10)\n        response_json = post_response.json()\n    \n        allure.attach(str(response_json), name=\"Invalid Token Response\", attachment_type=allure.attachment_type.JSON)\n    \n        assert post_response.status_code == 401\n>       validate(instance=response_json, schema=error_schema)\n\ntests/test_users_negative.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ninstance = {'message': 'Invalid token'}\nschema = {'items': {'properties': {'field': {'type': 'string'}, 'message': {'type': 'string'}}, 'required': ['message'], 'type': 'object'}, 'type': 'array'}\ncls = <class 'jsonschema.validators.Draft202012Validator'>, args = (), kwargs = {}\nvalidator = Draft202012Validator(schema={'items': {'properties': {'field': {'type': 'string'}, 'message': {'type': 'string'}}, 'required': ['message'], 'type': 'object'}, 'type': 'array'}, format_checker=None)\nerror = <ValidationError: \"{'message': 'Invalid token'} is not of type 'array'\">\n\n    def validate(instance, schema, cls=None, *args, **kwargs):  # noqa: D417\n        \"\"\"\n        Validate an instance under the given schema.\n    \n            >>> validate([2, 3, 4], {\"maxItems\": 2})\n            Traceback (most recent call last):\n                ...\n            ValidationError: [2, 3, 4] is too long\n    \n        :func:`~jsonschema.validators.validate` will first verify that the\n        provided schema is itself valid, since not doing so can lead to less\n        obvious error messages and fail in less obvious or consistent ways.\n    \n        If you know you have a valid schema already, especially\n        if you intend to validate multiple instances with\n        the same schema, you likely would prefer using the\n        `jsonschema.protocols.Validator.validate` method directly on a\n        specific validator (e.g. ``Draft202012Validator.validate``).\n    \n    \n        Arguments:\n    \n            instance:\n    \n                The instance to validate\n    \n            schema:\n    \n                The schema to validate with\n    \n            cls (jsonschema.protocols.Validator):\n    \n                The class that will be used to validate the instance.\n    \n        If the ``cls`` argument is not provided, two things will happen\n        in accordance with the specification. First, if the schema has a\n        :kw:`$schema` keyword containing a known meta-schema [#]_ then the\n        proper validator will be used. The specification recommends that\n        all schemas contain :kw:`$schema` properties for this reason. If no\n        :kw:`$schema` property is found, the default validator class is the\n        latest released draft.\n    \n        Any other provided positional and keyword arguments will be passed\n        on when instantiating the ``cls``.\n    \n        Raises:\n    \n            `jsonschema.exceptions.ValidationError`:\n    \n                if the instance is invalid\n    \n            `jsonschema.exceptions.SchemaError`:\n    \n                if the schema itself is invalid\n    \n        .. rubric:: Footnotes\n        .. [#] known by a validator registered with\n            `jsonschema.validators.validates`\n    \n        \"\"\"\n        if cls is None:\n            cls = validator_for(schema)\n    \n        cls.check_schema(schema)\n        validator = cls(schema, *args, **kwargs)\n        error = exceptions.best_match(validator.iter_errors(instance))\n        if error is not None:\n>           raise error\nE           jsonschema.exceptions.ValidationError: {'message': 'Invalid token'} is not of type 'array'\nE           \nE           Failed validating 'type' in schema:\nE               {'type': 'array',\nE                'items': {'type': 'object',\nE                          'properties': {'field': {'type': 'string'},\nE                                         'message': {'type': 'string'}},\nE                          'required': ['message']}}\nE           \nE           On instance:\nE               {'message': 'Invalid token'}\n\nvenv/lib/python3.12/site-packages/jsonschema/validators.py:1332: ValidationError"}, "description": "Verify creating a user with an invalid token fails (401)", "attachments": [{"name": "Invalid Token Response", "source": "77a83cc3-49b6-463f-b38f-4fc16ff040a8-attachment.json", "type": "application/json"}], "start": 1757596490173, "stop": 1757596490797, "uuid": "e93d68a0-955c-43e8-8281-2c83b545c170", "historyId": "835ce4bbef170a855e338b21bdd139df", "testCaseId": "835ce4bbef170a855e338b21bdd139df", "fullName": "tests.test_users_negative#test_create_user_invalid_token", "labels": [{"name": "story", "value": "Negative Scenarios"}, {"name": "feature", "value": "User Management"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users_negative"}, {"name": "host", "value": "riju-Inspiron-15-3515"}, {"name": "thread", "value": "569533-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users_negative"}], "titlePath": ["tests", "test_users_negative.py"]}